This is a project that is going to utilize the use of Multivariate Regression to come up with investment decisions on the Property Market.
In reality we can speculate on many different aspects that can influence our decisions when purchasing properties, this project is going to take full advantage of making data driven decisions.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as sm

Importing the necessary data for our regress model analysis.

In [ ]:
data = pd.read_excel(r"C:\Users\obien\OneDrive\Desktop\Projects\Regression_Analysis\Housing.xlsx")
data

,House Price,House Size (sq.ft.),State,Number of Rooms,Year of Construction
0,1116000,1940,IN,8,2002
1,860000,1300,IN,5,1992
2,818400,1420,IN,6,1987
3,1000000,1680,IN,7,2000
4,640000,1270,IN,5,1995
5,1010000,1850,IN,7,1998
6,600000,1000,IN,4,2015
7,700000,1100,LA,4,2014
8,1100000,1600,LA,7,2017
9,570000,1000,NY,5,1997
10,860000,2150,NY,9,1997
11,1085000,1900,NY,9,2000
12,1250000,2200,NY,9,2014
13,850000,1100,TX,4,2017
14,640000,860,TX,4,1997
15,900000,1325,TX,6,1997
16,730000,1350,TX,6,2000
17,750000,1600,TX,6,1992
18,650000,950,TX,2,1987
19,680000,1250,TX,4,2000

Assigning independent and dependant variables for the model.

In [ ]:
x = data[['House Size (sq.ft.)', 'Number of Rooms', 'Year of Construction']]
y = data['House Price']

Running and initializing the model using OLS(Ordinary Least Squares) method to get the model.

In [ ]:
x1 = sm.add_constant(x)
reg = sm.OLS(y, x1).fit()
reg.summary()

C:\Users\obien\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            House Price   R-squared:                       0.736
Model:                            OLS   Adj. R-squared:                  0.687
Method:                 Least Squares   F-statistic:                     14.90
Date:                Sat, 29 Jan 2022   Prob (F-statistic):           6.82e-05
Time:                        16:03:01   Log-Likelihood:                -258.43
No. Observations:                  20   AIC:                             524.9
Df Residuals:                      16   BIC:                             528.9
Df Model:                           3
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                -9.452e+06    5.4e+06     -1.752      0.099   -2.09e+07    1.99e+06
House Size (sq.ft.)    341.8271    179.666      1.903      0.075     -39.049     722.703
Number of Rooms        1.16e+04   3.74e+04      0.310      0.760   -6.77e+04    9.08e+04
Year of Construction  4863.5761   2697.969      1.803      0.090    -855.862    1.06e+04
==============================================================================
Omnibus:                        2.140   Durbin-Watson:                   1.938
Prob(Omnibus):                  0.343   Jarque-Bera (JB):                1.747
Skew:                          -0.676   Prob(JB):                        0.418
Kurtosis:                       2.484   Cond. No.                     5.40e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.4e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Analysis
The table of results shows what influences the price of a property.